'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import type {Photo} from '@/lib/photo-metadata';
import {parameterSummary,visibleTitle,parameterFields} from '@/lib/photo-metadata';
import {usePreference} from '../../hooks/usePreference';
import {useLanguage} from '../../hooks/useLanguage';
import {formatBilingualText} from '../../locales/metadata-helpers';
import './justified.css';
import {photoRatios,stopLayoutMotion} from '@/lib/gallery-motion';
const validHeight=(value:string):value is string=>Number(value)>=160&&Number(value)<=480;
export function useThumbnailHeight(defaultHeight=280){
 return usePreference('gallery-lr-thumbnail-height',String(defaultHeight),validHeight);
}
export function ThumbnailSizeControl(){
 const [height,setHeight]=useThumbnailHeight();
 const {t}=useLanguage();
 const input=useRef<HTMLInputElement>(null),frame=useRef<number|null>(null),pending=useRef<string|null>(null);
 const commit=()=>{if(frame.current!==null){cancelAnimationFrame(frame.current);frame.current=null;}if(pending.current!==null){setHeight(pending.current);pending.current=null;}};
 useEffect(()=>{if(frame.current===null&&input.current)input.current.value=height;},[height]);
 useEffect(()=>()=>{if(frame.current!==null)cancelAnimationFrame(frame.current);},[]);
 return <label className="addon-justified-slider-wrap"><span>{t('缩略图大小','Thumbnail size')}</span><input ref={input} type="range" min="160" max="480" step="10" defaultValue={height} style={{'--slider-fill':`${(Number(height)-160)/3.2}%`} as React.CSSProperties} onPointerDown={stopLayoutMotion} onKeyDown={stopLayoutMotion} onChange={e=>{pending.current=e.target.value;e.target.style.setProperty('--slider-fill',`${(Number(e.target.value)-160)/3.2}%`);if(frame.current===null)frame.current=requestAnimationFrame(()=>{frame.current=null;if(pending.current!==null)setHeight(pending.current,false);});}} onPointerUp={commit} onPointerCancel={commit} onKeyUp={commit} onBlur={commit} className="addon-justified-slider" aria-label={t('调节照片缩略图大小','Thumbnail size')}/></label>;
}

export default function JustifiedGallery({photos,onViewPhoto,defaultRowHeight=280,manage=false,selectedIds,disabled=false,classic=false,onReorder,showSelectionOrder=false}:{photos:Photo[];onViewPhoto:(id:string,opener:HTMLElement)=>void;defaultRowHeight?:number;manage?:boolean;selectedIds?:readonly string[];disabled?:boolean;classic?:boolean;showSelectionOrder?:boolean;onReorder?:(from:string,to:string)=>void}){
 const container=useRef<HTMLDivElement>(null);
 const [width,setWidth]=useState(0),[ratios,setRatios]=useState<Record<string,number>>(()=>Object.fromEntries(photoRatios));
 const [height]=useThumbnailHeight(defaultRowHeight);
 const {lang,t}=useLanguage();
 useLayoutEffect(()=>{const el=container.current;if(!el)return;setWidth(el.getBoundingClientRect().width);const observer=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));observer.observe(el);return()=>observer.disconnect();},[classic]);
 const positions=new Map(photos.map((photo,index)=>[photo.id,index]));
 const gap=classic?4:0;
 const rows:{photos:Photo[];height:number}[]=[];let pending:Photo[]=[],sum=0;
 for(const p of photos){pending.push(p);sum+=ratios[p.id]||1.5;if(sum*Number(height)+gap*(pending.length-1)>=width&&width>0){rows.push({photos:pending,height:(width-gap*(pending.length-1))/sum});pending=[];sum=0;}}
 if(pending.length)rows.push({photos:pending,height:Math.min(Number(height),(width-gap*(pending.length-1))/sum)});
 return <div className={`addon-justified-wrapper${classic?" addon-justified-classic":""}`} ref={container}><div className="addon-justified-container stable-photo-layout" style={{columnGap:gap}} aria-label={t('通栏画廊视图','Justified gallery')}>{rows.flatMap((row,i)=>[...(i?[<span className="justified-break" key={"break:"+i} aria-hidden="true"/>]:[]),...row.photos.map(p=>{const cardWidth=Math.max(1,row.height*(ratios[p.id]||1.5));const exif=cardWidth<320?parameterSummary({focalLength:p.exif.focalLength,aperture:p.exif.aperture,shutter:p.exif.shutter,iso:p.exif.iso}):parameterSummary(p.exif);const title=formatBilingualText(p.title,lang);const captionTitle=formatBilingualText(visibleTitle(p.title),lang);const meta=[formatBilingualText(p.location,lang)].filter(Boolean).join(' · ');const photoIndex=positions.get(p.id)??0;return <article key={p.id} className="addon-justified-card" data-gallery-photo={p.id} draggable={manage&&!!onReorder&&!disabled} onDragStart={e=>{e.dataTransfer.setData('text/gallery-photo',p.id);e.dataTransfer.effectAllowed='move';const count=selectedIds?.includes(p.id)?selectedIds.length:1;if(count>1){const ghost=e.currentTarget.cloneNode(true) as HTMLElement;ghost.className='gallery-drag-stack';ghost.style.width='180px';const badge=document.createElement('span');badge.textContent=String(count);ghost.appendChild(badge);document.body.appendChild(ghost);e.dataTransfer.setDragImage(ghost,90,60);requestAnimationFrame(()=>ghost.remove());}e.currentTarget.dataset.dragging='true';}} onDragEnd={e=>{delete e.currentTarget.dataset.dragging;document.querySelectorAll('[data-drop-target]').forEach(el=>el.removeAttribute('data-drop-target'));}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))delete e.currentTarget.dataset.dropTarget;}} onDragOver={e=>{if(onReorder&&!disabled){e.preventDefault();e.currentTarget.dataset.dropTarget='true';}}} onDrop={e=>{e.preventDefault();delete e.currentTarget.dataset.dropTarget;const id=e.dataTransfer.getData('text/gallery-photo');if(id&&id!==p.id&&!disabled)onReorder?.(id,p.id);}} style={{width:cardWidth,viewTransitionName:'gallery-photo-'+p.id.replace(/[^a-zA-Z0-9_-]/g,'')}}><button type="button" className="addon-justified-item" disabled={disabled} style={{width:"100%",height:Math.max(1,row.height)}} aria-pressed={selectedIds?selectedIds.includes(p.id):undefined} aria-label={selectedIds?t('选择 '+title,'Select '+title):manage?t('编辑 '+title,'Edit '+title):t('查看 '+title,'View '+title)} onClick={e=>onViewPhoto(p.id,e.currentTarget)}>
 {/* eslint-disable-next-line @next/next/no-img-element */}
 <img data-morph-photo={p.id} src={'/api/image/'+p.id} alt={title} className="addon-justified-img" draggable={false} loading="lazy" onLoad={e=>{const img=e.currentTarget;const ratio=img.naturalWidth/img.naturalHeight;if(Number.isFinite(ratio)&&ratio>0){photoRatios.set(p.id,ratio);setRatios(old=>old[p.id]===ratio?old:{...old,[p.id]:ratio});}}}/>{selectedIds&&<span aria-hidden="true" style={{position:'absolute',top:10,left:10,zIndex:2,width:24,height:24,background:selectedIds.includes(p.id)?'var(--ink)':'#fff',color:'var(--paper)',border:'1px solid #888',display:'grid',placeItems:'center'}}>{selectedIds.includes(p.id)?showSelectionOrder?selectedIds.indexOf(p.id)+1:'✓':''}</span>}{!classic&&<div className="addon-justified-overlay" aria-hidden="true">{meta&&<h3 className="addon-justified-title">{meta}</h3>}<p className="addon-justified-sub">{exif||t('未提供拍摄参数','No camera settings')}</p></div>}</button>{classic&&<><div className="addon-caption"><div>{captionTitle&&<h3 className="addon-photo-title">{captionTitle}</h3>}{meta&&<p className="addon-photo-sub">{meta}</p>}</div><span className="addon-index">{String(photoIndex+1).padStart(2,"0")}</span></div>{parameterSummary(p.exif)&&<div className="addon-classic-exif" aria-label="EXIF" title={parameterSummary(p.exif)}>{["camera","lens"].map(key=>{const value=p.exif[key as "camera"|"lens"];return value?<span className="addon-classic-equipment" key={key}>{value}</span>:null;})}<div className="addon-classic-settings">{parameterFields.filter(f=>f.key!=="camera"&&f.key!=="lens"&&p.exif[f.key]).map(f=><span key={f.key}>{p.exif[f.key]}</span>)}</div></div>}</>}</article>})])}</div></div>;
}
